### ISSUE TITLE
回答メール、ルーム管理者とかのみX-URL付ける対応

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/Mails#88]
### NC2登録フォーム

対応していた。

![image](https://cloud.githubusercontent.com/assets/2756509/16796355/478e9780-491d-11e6-94e2-2cb7f60aaf01.png)

さて、どう対応したものかな。

**Comment by akagane99** [comment]
こんな感じの対応案でいけるかも。

### NC3対応案

* メール定型文末尾に、承認者？のみ表示するメッセージを追加できるように、MailQueueBehaviorに機能追加。
* save直前にsetSettingで末尾定型文をセットする想定。
* 実装プラグイン側の言語ファイルに、末尾定型文をもつ
```
例）
msgid "mail_fixed_phrase_body_after"
msgstr "\n"
"\n"
"登録内容確認画面URL\n"
"{X-URL}"
```

**Comment by RyujiAMANO** [comment]
末尾定型文はTO_ADDRESSES宛からは外れる感じですね。

**Comment by akagane99** [comment]
yes!
